export { default as GaIconPrimaryArrowLong } from './arrow-long.vue'
export { default as GaIconPrimaryArrow } from './arrow.vue'
export { default as GaIconPrimaryLogo } from './logo.vue'
export { default as GaIconPrimaryMarketAppGallery } from './market-app-gallery.vue'
export { default as GaIconPrimaryMarketAppStore } from './market-app-store.vue'
export { default as GaIconPrimaryMarketGooglePlay } from './market-google-play.vue'
export { default as GaIconPrimaryMarketRuStore } from './market-ru-store.vue'
export { default as GaIconPrimaryStar } from './star.vue'
